#!/bin/sh

# TODO:
# o There's some encoding bug with non-ASCII characters interoperating with namecoin.  Predicted size can be
#   invalid, resulting in uninsertable documents.
# o Namecoin needs a way to notify user that the balance is insufficient.
# o Add a script to gpg sign the documents, so that it is harder to change them
#   while waiting on the queue, in case computer is offline -- this'll take
#   some thought.  Only one sig needed if they have each other hashed.
# o Investigate why -xf may produce longer document chains than -xb
# o Improve -xf, -xb such that the output may be presented in reverse order with -xb, and perhaps require this.  Reverse order is useful for storage
#   that places the last item on top to be read easily.
# o Port to C or some language better suited
# o Organize and generalize functions which manage split documents; code is mixed up -> prioritize understandability (simplicity)
#   One idea is adding formatter functions which save/restore state and provide an end-of-document state
# o Make the inverse tool to this tool, which reads the output and checks it, filtering commands that are not deterministic
#   This is also important because I briefly saw an issue where split documents were not properly inserted.
# o Add a binary formatter? xml formatter?  Binary could be so tiny for namecoin, which would save money and ease use.  include plain url in binary output?
# o Verify and enforce namecoin itself -> it must regularly produce blocks with proper difficulty that contain our documents, and provide notice otherwise
#   This can be done here or preferably in bitcoin core itself, perhaps somebody has already.  If so link it.


#### Main initialization at bottom.

SCRIPTNAME="uvfy"
uvfy_version() {
  echo "$SCRIPTNAME 0.2.4  https://github.com/xloem/uvfy"
}

uvfy_help() {
  echo "Usage: $SCRIPTNAME [options] script [args...] [-- script2 [args...] ...]"
  echo "Presents metadata chosen by each script specified."
  echo
  echo "  -f,  --format format     Output format, currently only json supported"
  echo "  -l,  --label label       Output label, default "uvfy", not always used"
  echo "  -p,  --full-paths        Output entire paths for filenames"
  echo "       --gpg path-to-gpg   Path to gpg binary for signature verification"
  echo "  -xb, --hash-backward     Include in each output the hash of the last"
  echo "  -xf, --hash-forward      Inverse of -xb, uses hash of the next output."
  echo "                           More precise storage time if output saved in order."
  echo "  -x,  --hashes programs   Comma-separated list of checksum programs to"
  echo "                           calculate hashes.  Default: sha512sum"
  echo "       --help              Display this help message"
  echo "  -s,  --max-size size     Split output that would exceed size"
	echo "  -y,  --pretty            Prettify formatted output"
  echo "  -V,  --version           Display $SCRIPTNAME version"
  echo "  -- script.uvfy [...]    Provide further scripts to execute."
  echo "                          Note that -- is required between scripts"
  echo
  echo "Options affect only the scripts following them on the command line."
  echo
  echo "Included scripts: "
  for script in "$UVFY_HOME/scripts/"*.uvfy
  do
    script="${script##*/}"
    echo -n " ${script%.uvfy}"
  done
  echo
}

#### Default configuration

UVFY_BASE_LABEL="uvfy"
UVFY_OUTPUT_MODE="json"
UVFY_GPG="gpg2"
UVFY_HASHES="sha512sum"
UVFY_SKIP_DIGITS="2"
if test -z "$UVFY_HOME"
then
  for uvfy_possibility in \
    "$(dirname "$(readlink -f "$(type -p "$0")")")" \
    "/usr/local/share/uvfy" "/usr/share/uvfy"
  do
    if test -d "$uvfy_possibility"/scripts
    then
      UVFY_HOME="$uvfy_possibility"
      break
    fi
  done
fi
if ! test -d "$UVFY_HOME/scripts"
then
  echo "ERROR: No such directory '$UVFY_HOME/scripts'" 1>&2
  echo "       Is UVFY_HOME="$UVFY_HOME" correct?" 1>&2
  exit 2
fi
if ! (
  cd "$UVFY_HOME"
  sha512sum -c <<EOF >/dev/null
c461613db2bb41b244259b0bdfebaeeb3a55ea4287792fe8a7ab0cc8a67876fee41d590cc4974d949a95477154ba10d30d9919c00e4bd939d9b5b11937945021  scripts/dar-backup.uvfy
f4aabde48116db67f13b6413a396c5ee7b805f3bb2a928434741323ab47d999575b35327681ac15b77987c5da87a3a31e5261d55eb3c7e0d79d06ee20d4cff18  scripts/git-add-commit.uvfy
c4e1bb799dd02c957c12bd2a3c005a9ba8e0950c1c8957b86887670cb7cbd467110324739e355890bade6d309f4417c7cdea42b7c56263aa3b360926efba6382  scripts/git-status.uvfy
e6caeed526a7fc90da5a9c6b1434523a6774b944181ca4cb7cb5a449e572b89914fe6ea76d331ca43ec46fb88a0252c4004cdff090f19b453f7377c3340ed219  scripts/invocation.uvfy
af3041b43d82435d6a604821e8496c7c7f2500a03903f332ec5dd652cb7697b0387a1555af0918e0d8d796ae2e1a89142bcfdfdc5a5738a43182b132fa481ef9  scripts/loop-mount.uvfy
57aafa3c20619f4d0115963db975c903c1b5bac00a7d6f9c1446ec9fcf4eddf3b7f2c5b91196c5bd1b6d3948e42403b713536a95dddf34058bff5d16e7d6044a  scripts/nested-image.uvfy
d084ec9349f108ba0ad0d1343fd84edfc5ba091b09d6a2276da5662196742d1e00bece6cb52adda4822665549f3b76f155fd3fd50ee6b0f97bc55c9d2e0b0c01  scripts/single-file.uvfy
84c1b67b82e736178a940768f5e41684c0276f552f528df1762075204b64bdfa0b333aa66a0cf4c0a72fd0f468421fe5d430cfbff9f712f8d3fd43806df45cd7  scripts/store-namecoin.uvfy
EOF
)
then
  echo "ERROR: Scripts failed checksum." 1>&2
  exit 2
fi


#### Output functions to be used by scripts

uvfy_filecontents_fullpaths() {
  cached__UVFY_FULL_PATHS="$UVFY_FULL_PATHS"
  UVFY_FULL_PATHS=1
  uvfy_filecontents "$@"
  UVFY_FULL_PATHS="$cached__UVFY_FULL_PATHS"
}

uvfy_filecontents() {
  for uvfy_filename in "$@"
  do
    uvfy_output_itemstart
    if uvfy_has_grepline "$uvfy_filename"
    then
      uvfy_filename="$uvfy_last_without_grepline"
      if ! uvfy_output_file_has_been_hashed "$uvfy_filename"
      then
        uvfy_output_filename_element "$uvfy_filename"
        uvfy_output_filesize_element "$uvfy_filename"
        uvfy_output_file_hashes "$uvfy_filename"
      else
        uvfy_output_filename_element "$uvfy_filename"
      fi
      uvfy_output_cmd_elements grep grep $uvfy_last_grepline "$uvfy_filename" || continue
    else
      uvfy_output_filename_element "$uvfy_filename"
      uvfy_output_cmd_elements cat cat "$uvfy_filename" || continue
    fi

    # if filename ends in asc or sig, verify it as a signature
    if test "${uvfy_filename%.sig}" != "$uvfy_filename" || test "${uvfy_filename%.asc}" != "$uvfy_filename"
    then
      if "$UVFY_GPG" --list-packets < "$uvfy_filename" > "$UVFY_OUTPUT_CMDFILE" 2>/dev/null
      then
        if ! grep -q 'public key packet' < "$UVFY_OUTPUT_CMDFILE"
        then
          if test -z "$UVFY_OUTPUT_GPG_VERSION"
          then
            UVFY_OUTPUT_GPG_VERSION=1
            UVFY_OUTPUT_CMDFILTER=uvfy_output_cmdfilter_head\ -n2
            uvfy_output_cmd_elements "gpg-version" "$UVFY_GPG" --version
          fi
          UVFY_OUTPUT_CMDFILTER=uvfy_output_cmdfilter_trimgpg
          uvfy_output_cmd_elements "gpg-verify" "$UVFY_GPG" --verify "$uvfy_filename"
          UVFY_OUTPUT_CMDFILTER=cat
          uvfy_fingerprint="$(grep "Primary key fingerprint" "$UVFY_OUTPUT_CMDFILE")"
          if test -n "$uvfy_fingerprint"
          then
            uvfy_fingerprint="${uvfy_fingerprint#Primary key fingerprint:}"
            uvfy_fingerprint="${uvfy_fingerprint// /}"
            uvfy_output_element "gpg-fingerprint" "$uvfy_fingerprint"
          fi
        fi
      fi
    fi
    uvfy_output_itemend
  done
}

uvfy_filehashes_nofullpaths() {
  cached__UVFY_FULL_PATHS="$UVFY_FULL_PATHS"
  unset UVFY_FULL_PATHS
  UVFY_FULL_PATHS=1
  uvfy_filehashes "$@"
  UVFY_FULL_PATHS="$cached__UVFY_FULL_PATHS"
  unset cached__UVFY_FULL_PATHS
}

uvfy_filehashes_fullpaths() {
  cached__UVFY_FULL_PATHS="$UVFY_FULL_PATHS"
  UVFY_FULL_PATHS=1
  uvfy_filehashes "$@"
  UVFY_FULL_PATHS="$cached__UVFY_FULL_PATHS"
  unset cached__UVFY_FULL_PATHS
}

uvfy_filehashes() {
  for uvfy_filename in "$@"
  do
    if uvfy_output_file_has_been_hashed "$uvfy_filename"
    then
      continue
    fi
    uvfy_output_itemstart
    uvfy_output_filename_element "$uvfy_filename"
    uvfy_output_filesize_element "$uvfy_filename"
    uvfy_output_file_hashes "$uvfy_filename"
    uvfy_output_itemend
  done
}

uvfy_filehashes_nosize() {
  cached__uvfy_filename="$uvfy_filename"
  for uvfy_filename in "$@"
  do
    if uvfy_output_file_has_been_hashed "$uvfy_filename"
    then
      continue
    fi
    uvfy_output_itemstart
    uvfy_output_filename_element "$uvfy_filename"
    uvfy_output_file_hashes "$uvfy_filename"
    uvfy_output_itemend
  done
  uvfy_filename="$cached__uvfy_filename"
  unset cached__uvfy_filename
}

uvfy_filehashes_nosize_nofullpaths() {
  cached__UVFY_FULL_PATHS="$UVFY_FULL_PATHS"
  unset UVFY_FULL_PATHS
  uvfy_filehashes_nosize "$@"
  UVFY_FULL_PATHS="$cached__UVFY_FULL_PATHS"
  unset cached__UVFY_FULL_PATHS
}

# A command which produces no new files
# uvfy_cmdoutput cmd[::grepfor] [args ...]
uvfy_cmdoutput() {
  uvfy_output_itemstart
  if uvfy_has_grepline "$1"
  then
    shift
    set -- "$uvfy_last_without_grepline" "$@"
    UVFY_OUTPUT_CMDFILTER="grep $uvfy_last_grepline"
    uvfy_output_array cmd "$@"
    uvfy_output_cmd_elements grep "$@"
    UVFY_OUTPUT_CMDFILTER="cat"
  else
    uvfy_output_array cmd "$@"
    uvfy_output_cmd_elements out "$@"
  fi
  uvfy_exit_status=$?
  uvfy_output_itemend
  return $uvfy_exit_status
}

# Save the output of a command to a new file
# uvfy_write_cmd file cmd [args ...]
uvfy_write_cmd() {
  cached__UVFY_OUTPUT_CMDFILE_AUX="$UVFY_OUTPUT_CMDFILE_AUX"
  UVFY_OUTPUT_CMDFILE_AUX="$1"
  shift
  UVFY_OUTPUT_CMDCAPTURE=stderr
  uvfy_output_itemstart
  uvfy_output_array cmd "$@"
  uvfy_output_element write "$UVFY_OUTPUT_CMDFILE_AUX"
  uvfy_output_cmd_elements err "$@"
  uvfy_exit_status=$?
  UVFY_OUTPUT_CMDCAPTURE=combined
  UVFY_OUTPUT_CMDFILE_AUX="$cached__UVFY_OUTPUT_CMDFILE_AUX"
  unset cached__UVFY_OUTPUT_CMDFILE_AUX
  uvfy_output_itemend
  return $uvfy_exit_status
}

uvfy_invocationargsarray() {
  uvfy_output_itemstart
  uvfy_with_flatlist_parameters uvfy_output_array "$(uvfy_flatlist_prepended argv "$0" "$UVFY_OUTPUT_ARGS")"
  uvfy_output_itemend
}


#### general utility functions

uvfy_number_pad() {
  padded="$1"
  digits="${2:-5}"
  while test "${#padded}" -lt "$digits"
  do
    padded="0$padded"
  done
  echo "$padded"
}

uvfy_number_unpad() {
  padded=""
  unpadded="$1"
  while test "$padded" != "$unpadded"
  do
    padded="$unpadded"
    unpadded="${padded#0}"
  done
  if test -n "$unpadded"
  then
    echo "$unpadded"
  else
    echo "0"
  fi
}

uvfy_quote() {
  echo -n "'${1//\'/\'\\\'\'}' "
}


uvfy_in_flatlist() {
  uvfy_value="$1"
  eval "set -- $2"
  for uvfy_comparison in "$@"
  do
    if test "$uvfy_comparison" == "$uvfy_value"
    then
      return 0
    fi
  done
  return 1
}

uvfy_flatlist_prepended() {
  uvfy_value="$1"
  shift
  for uvfy_value_next in "$@"
  do
    uvfy_quote "$uvfy_value"
    uvfy_value="$uvfy_value_next"
  done
  echo -n "$uvfy_value"
}

uvfy_flatlist_appended() {
  uvfy_list="$1"
  shift
  echo -n "$uvfy_list"
  uvfy_as_flatlist "$@"
}

uvfy_flatlist_added_unique() {
  uvfy_list="$1"
  shift
  echo -n "$uvfy_list"
  for uvfy_value in "$@"
  do
    if ! uvfy_in_flatlist "$uvfy_value" "$uvfy_list"
    then
      uvfy_quote "$uvfy_value"
    fi
  done
}

uvfy_as_flatlist() {
  for uvfy_value in "$@"
  do
    uvfy_quote "$uvfy_value"
  done
}

# WARNING: passes $* to eval, all parameters except $1 should be uvfy_quoted
uvfy_with_flatlist_parameters() {
  cmd="$1"
  shift
  eval "set -- $*"
  "$cmd" "$@"
}


#### internal utility functions for outputing command results

UVFY_OUTPUT_CMDCAPTURE=combined
UVFY_OUTPUT_CMDFILTER=cat
UVFY_OUTPUT_STREAMING_MODE=tee
UVFY_OUTPUT_PRESENTATION_MODE=none
UVFY_OUTPUT_HASHED_FILES=
UVFY_OUTPUT_COMMANDS_RUN=
UVFY_FLATLIST_DELIMITER='
+
'

uvfy_output_file_for_index() {
  echo "${UVFY_OUTPUT_TMPDIR}"/"$UVFY_LABEL".$(uvfy_number_pad $1 $UVFY_SKIP_DIGITS)."$UVFY_OUTPUT_MODE"
}

uvfy_output_file_no_index() {
  echo "${UVFY_OUTPUT_TMPDIR}"/"$UVFY_LABEL"."$UVFY_OUTPUT_MODE"
}

uvfy_has_grepline() {
  uvfy_last_grepline="${1#*::}"
  uvfy_last_without_grepline="${1%%::*}"
  test "$uvfy_last_grepline" != "$1"
}

uvfy_output_file_has_been_hashed() {
  uvfy_filename="$1"
  if ! uvfy_in_flatlist "$uvfy_filename" "$UVFY_HASHED_FILES"
  then
    UVFY_HASHED_FILES="$(uvfy_flatlist_added_unique "$UVFY_HASHED_FILES" "$uvfy_filename")"
    false
  fi
}

uvfy_output_filesize_element() {
  uvfy_output_cmd_elements "size" stat -L --format=%s "$uvfy_filename"
}

uvfy_output_file_hashes() {
  uvfy_filename="$1"
  UVFY_OUTPUT_CMDFILTER=uvfy_output_cmdfilter_firstword
  IFS=','
  set -- $UVFY_HASHES
  unset IFS
  uvfy_output_filecmd_elements "$uvfy_filename" "$@"
  UVFY_OUTPUT_CMDFILTER=cat
}


uvfy_output_filecmd_elements() {
  uvfy_filename="$1"
  shift
  for uvfy_cmd in "$@"
  do
    uvfy_output_cmd_elements "$uvfy_cmd" "$uvfy_cmd" <"$uvfy_filename"
  done
}

uvfy_output_run_cmd_combined() {
  "$@" > "$UVFY_OUTPUT_CMDFILE" 2>&1
}

uvfy_output_run_cmd_stderr() {
  "$@" 2> "$UVFY_OUTPUT_CMDFILE" > "$UVFY_OUTPUT_CMDFILE_AUX"
}

uvfy_output_run_cmd_stdout() {
  "$@" > "$UVFY_OUTPUT_CMDFILE" 2> "$UVFY_OUTPUT_CMDFILE_AUX"
}

uvfy_output_cmdfilter_firstword() {
  read uvfy_word uvfy_rest
  cat >/dev/null
  echo "$uvfy_word"
}

uvfy_output_cmdfilter_head() {
  head "$@"
}

uvfy_output_cmdfilter_trimgpg() {
  grep -v "WARNING" |
  grep -v "Primary key fingerprint" |
  grep -v "There is no indication that the signature belongs to the owner" 
}

# Labeled output of a command as just one or two elements.
uvfy_output_cmd_elements() {
  uvfy_label="$1"
  shift
  if uvfy_output_run_cmd_$UVFY_OUTPUT_CMDCAPTURE "$@"
  then
    uvfy_output="$($UVFY_OUTPUT_CMDFILTER < "$UVFY_OUTPUT_CMDFILE")"
    if test -n "$uvfy_output"
    then
      uvfy_output_element "$uvfy_label" "$uvfy_output"
    else
      uvfy_output_element "exit" "OK"
    fi
  else
    uvfy_exit_status=$?
    uvfy_output_element "err" "$(cat "$UVFY_OUTPUT_CMDFILE")"
    uvfy_output_element "exit" "$uvfy_exit_status"
    UVFY_ERROR=$uvfy_exit_status
    return $uvfy_exit_status
  fi
  return 0
}

uvfy_output_filename_element() {
  if test -n "$UVFY_FULL_PATHS"
  then
    uvfy_output_element "file" "$1"
  else
    uvfy_output_element "file" "${1##*/}"
  fi
}



#### output formatter functions

uvfy_output_stream() {
  uvfy_tmpfile="${UVFY_OUTPUT_TMPDIR}/output_stream"
  "$@" > "$uvfy_tmpfile"
  uvfy_output_stream_$UVFY_OUTPUT_STREAMING_MODE < "$uvfy_tmpfile"
}
uvfy_output_stream_cache() {
  cat >> "$UVFY_OUTPUT_CACHE"
}
uvfy_output_stream_store() {
  cat >> "$UVFY_OUTPUT_FILE"
}
uvfy_output_stream_tee() {
  tee -a "$UVFY_OUTPUT_FILE"
}
uvfy_output_present_none() {
  true
}

uvfy_output_initialize() {
  if test -n "$UVFY_OUTPUT_INITIALIZED"
  then
    return 1
  fi
  UVFY_OUTPUT_INITIALIZED=1
  UVFY_OUTPUT_TMPDIR="$(mktemp -t -d uvfy.XXXXXX)"
  UVFY_OUTPUT_INDEX=1
  UVFY_OUTPUT_CMDFILE="${UVFY_OUTPUT_TMPDIR}/cmd_output"
  UVFY_OUTPUT_CMDFILE_AUX="${UVFY_OUTPUT_TMPDIR}/cmd_output_aux"
  UVFY_OUTPUT_ARGS="$(uvfy_as_flatlist "$@")"
  UVFY_LABEL="${UVFY_BASE_LABEL}-$(date +%s)"
  uvfy_output_initialize_"$UVFY_OUTPUT_MODE"
}
uvfy_output_start() {
  if test -n "$UVFY_OUTPUT_STARTED"
  then
    return 1
  fi
  UVFY_OUTPUT_STARTED=1
  if test -n "$UVFY_OUTPUT_SIZE"
  then
    UVFY_OUTPUT_FILE="$(uvfy_output_file_for_index $UVFY_OUTPUT_INDEX)"
  else
    UVFY_OUTPUT_FILE="$(uvfy_output_file_no_index)"
  fi
  UVFY_OUTPUT_CACHE="$UVFY_OUTPUT_FILE"_cache
  echo -n > "$UVFY_OUTPUT_FILE"
  echo -n > "$UVFY_OUTPUT_CACHE"
  if test -n "$UVFY_OUTPUT_SIZE" -a -z "$UVFY_OUTPUT_SIZE_CACHED"
  then
    UVFY_OUTPUT_SIZE_CACHED=1

    cached__UVFY_OUTPUT_SIZE="$UVFY_OUTPUT_SIZE"
    unset UVFY_OUTPUT_SIZE

    # an extra itemconnector so we can cache the next item without it when comparing
    # next size, in case it will start the next document
    uvfy_output_stream uvfy_output_itemconnector_$UVFY_OUTPUT_MODE

    if test "$UVFY_HASH_DIRECTION" == "1"
    then
      uvfy_filehashes_nosize_nofullpaths "$UVFY_OUTPUT_FILE"
    fi
    uvfy_output_stream uvfy_output_end_$UVFY_OUTPUT_MODE
    UVFY_OUTPUT_SIZE=$((cached__UVFY_OUTPUT_SIZE - $(stat --format=%s "$UVFY_OUTPUT_CACHE")))
    unset cached__UVFY_OUTPUT_CACHE
    mv "$UVFY_OUTPUT_CACHE" "${UVFY_OUTPUT_TMPDIR}/hash_size_example.json"
  fi
  uvfy_output_stream uvfy_output_start_"$UVFY_OUTPUT_MODE"
}
uvfy_output_itemstart() {
  # TODO code would be simplified if we used the caching paradigm with normal output as well as split output.
  if test -n "$UVFY_OUTPUT_SIZE"
  then
    UVFY_OUTPUT_STREAMING_MODE="cache"
    uvfy_output_start
  elif ! uvfy_output_start
  then
    uvfy_output_stream uvfy_output_itemconnector_"$UVFY_OUTPUT_MODE"
  fi
  uvfy_output_stream uvfy_output_itemstart_"$UVFY_OUTPUT_MODE"
}
uvfy_output_element() {
  uvfy_output_stream uvfy_output_element_"$UVFY_OUTPUT_MODE" "$@"
}
uvfy_output_array() {
  uvfy_output_stream uvfy_output_array_"$UVFY_OUTPUT_MODE" "$@"
}
uvfy_output_itemend() {
  uvfy_output_stream uvfy_output_itemend_"$UVFY_OUTPUT_MODE"
  if test -n "$UVFY_OUTPUT_SIZE"
  then
    if test "$UVFY_HASH_DIRECTION" == "1"
    then
      UVFY_OUTPUT_STREAMING_MODE="store"
    else
      UVFY_OUTPUT_STREAMING_MODE="tee"
    fi
    if test $(($(stat --format=%s "$UVFY_OUTPUT_FILE") + $(stat --format=%s "$UVFY_OUTPUT_CACHE"))) -gt $UVFY_OUTPUT_SIZE
    then
      if test "$UVFY_HASH_DIRECTION" == "1"
      then
        # prevent uvfy_output_end from closing the document
        # but ensure uvfy_output_start opens another
        unset UVFY_OUTPUT_STARTED
      fi
      UVFY_OUTPUT_CACHE_LAST="$UVFY_OUTPUT_CACHE"
      uvfy_output_end partial

      UVFY_OUTPUT_INDEX=$((UVFY_OUTPUT_INDEX + 1))

      if test "$UVFY_HASH_DIRECTION" == "-1"
      then
        uvfy_filehashes_nosize_nofullpaths "$(uvfy_output_file_for_index $((UVFY_OUTPUT_INDEX - 1)))"
        uvfy_output_stream uvfy_output_itemconnector_$UVFY_OUTPUT_MODE
      else
        uvfy_output_start
      fi

      cat "$UVFY_OUTPUT_CACHE_LAST" >> "$UVFY_OUTPUT_CACHE"
      rm "$UVFY_OUTPUT_CACHE_LAST"
      unset UVFY_OUTPUT_CACHE_LAST

      if test $(($(stat --format=%s "$UVFY_OUTPUT_FILE") + $(stat --format=%s "$UVFY_OUTPUT_CACHE"))) -gt $UVFY_OUTPUT_SIZE
      then
        echo "ERROR: item larger than maximum size (adjusted to $UVFY_OUTPUT_SIZE), see $UVFY_OUTPUT_CACHE" 1>&2
        exit 2
      fi

    elif test -s "$UVFY_OUTPUT_FILE"
    then
      uvfy_output_stream uvfy_output_itemconnector_"$UVFY_OUTPUT_MODE"
    fi
    uvfy_output_stream cat "$UVFY_OUTPUT_CACHE"
    echo -n > "$UVFY_OUTPUT_CACHE"
  fi
}
uvfy_output_end() {
  if test -z "$UVFY_OUTPUT_STARTED"
  then
    return 1
  fi
  uvfy_output_stream uvfy_output_end_"$UVFY_OUTPUT_MODE"
  unset UVFY_OUTPUT_STARTED
  if test "$UVFY_HASH_DIRECTION" != 1
  then
    uvfy_output_present_$UVFY_OUTPUT_PRESENTATION_MODE
    echo
  elif test -z "$1"
  then
    UVFY_OUTPUT_INDEX_END=$UVFY_OUTPUT_INDEX
    cached__UVFY_OUTPUT_SIZE="$UVFY_OUTPUT_SIZE"
    unset UVFY_OUTPUT_SIZE
    while test $UVFY_OUTPUT_INDEX -gt 1
    do
      UVFY_OUTPUT_STARTED=1
      UVFY_OUTPUT_INDEX=$((UVFY_OUTPUT_INDEX - 1))
      UVFY_OUTPUT_FILE="$(uvfy_output_file_for_index $UVFY_OUTPUT_INDEX)"
      uvfy_filehashes_nosize_nofullpaths "$(uvfy_output_file_for_index $((UVFY_OUTPUT_INDEX + 1)))"
      uvfy_output_stream uvfy_output_end_"$UVFY_OUTPUT_MODE"
    done
    UVFY_OUTPUT_STREAMING_MODE=tee
    while test $UVFY_OUTPUT_INDEX -le $UVFY_OUTPUT_INDEX_END
    do
      cat "$UVFY_OUTPUT_FILE" # emulates tee
      echo
      uvfy_output_present_$UVFY_OUTPUT_PRESENTATION_MODE
      UVFY_OUTPUT_INDEX=$((UVFY_OUTPUT_INDEX + 1))
      UVFY_OUTPUT_FILE="$(uvfy_output_file_for_index $UVFY_OUTPUT_INDEX)"
    done
    UVFY_OUTPUT_SIZE="$cached__UVFY_OUTPUT_SIZE"
    unset cached__UVFY_OUTPUT_SIZE
  fi
  if test -z "$1"
  then
    UVFY_OUTPUT_INDEX=1
  fi
}

uvfy_json_stringify() {
  value="${1//
/\\n}"
  echo -n "\"${value//\"/\\\"}\""
}
uvfy_output_initialize_json() {
	if test -n "$UVFY_OUTPUT_PRETTY"
	then
		UVFY_JSON_SPACE=" "
		UVFY_JSON_INDENT="	"
		UVFY_JSON_LINEBREAK="
"
	else
		UVFY_JSON_SPACE=""
		UVFY_JSON_INDENT="$UVFY_JSON_SPACE"
		UVFY_JSON_LINEBREAK=""
	fi
}
uvfy_output_start_json() {
  echo -n "[\"${UVFY_OUTPUT_FILE##*/}\",$UVFY_JSON_LINEBREAK"
}
uvfy_output_itemconnector_json() {
  echo -n ",$UVFY_JSON_LINEBREAK"
}
uvfy_output_itemstart_json() {
  echo -n "$UVFY_JSON_INDENT{"
  uvfy_json_elementcomma=''
}
uvfy_output_element_json() {
  echo -n "$uvfy_json_elementcomma$UVFY_JSON_LINEBREAK"
  echo -n "$UVFY_JSON_INDENT$UVFY_JSON_INDENT$(uvfy_json_stringify "$1"):$UVFY_JSON_SPACE$(uvfy_json_stringify "$2")"
  uvfy_json_elementcomma=','
}
uvfy_output_array_json() {
  echo -n "$uvfy_json_elementcomma$UVFY_JSON_LINEBREAK"
  echo -n "$UVFY_JSON_INDENT$UVFY_JSON_INDENT$(uvfy_json_stringify "$1"):${UVFY_JSON_SPACE}["
  uvfy_json_stringify "$2"
  shift 2
  for uvfy_json_element in "$@"
  do
    echo -n ",$UVFY_JSON_SPACE"
    uvfy_json_stringify "$uvfy_json_element"
  done
  echo -n ']'
  uvfy_json_elementcomma=','
}
uvfy_output_itemend_json() {
  echo -n "$UVFY_JSON_LINEBREAK"
  echo -n "$UVFY_JSON_INDENT}"
}
uvfy_output_end_json() {
  echo -n "$UVFY_JSON_LINEBREAK"
  echo -n "]$UVFY_JSON_LINEBREAK"
}

#### Main initialization

uvfy_fail_missing_components() {
  echo 'Components required found missing.' 1>&2
  for component in $@
  do
    echo -n "$component: "
    type -p "$component" || echo MISSING 1>&2
  done
  exit 2
}

uvfy_require_components() {
  type -p $* >/dev/null || uvfy_fail_missing_components $*
}


UVFY_SCRIPT=
uvfy_append_script_argument() {
  UVFY_SCRIPT=$(uvfy_flatlist_appended "$UVFY_SCRIPT" "$*")
}

uvfy_runscript() {
  if test -z "$UVFY_SCRIPT"
  then
    echo "ERROR: no script specified" 1>&2
    uvfy_help
    exit 2
  elif test -z "$*"
  then
    uvfy_with_flatlist_parameters uvfy_runscript "$UVFY_SCRIPT"
    return
  fi

  (
    IFS=','
    set -- $UVFY_GPG $UVFY_HASHES
    unset IFS
    uvfy_require_components return for case set unset source eval test echo read cat rm stat mktemp date tee grep head "$@"
  )

  UVFY_SCRIPT="$1"
  shift
  for uvfy_possibility in "$UVFY_SCRIPT" "$UVFY_SCRIPT".uvfy "$UVFY_HOME/scripts/$UVFY_SCRIPT" "$UVFY_HOME/scripts/$UVFY_SCRIPT".uvfy
  do
    if test -r "$uvfy_possibility" -a -f "$uvfy_possibility"
    then
      UVFY_SCRIPT="$uvfy_possibility"
      break
    fi
  done
  unset uvfy_possibility
  if test -n "$UVFY_HASH_SCRIPTS"
  then
    uvfy_filehashes "$UVFY_SCRIPT"
  fi
  if ! source "$UVFY_SCRIPT" "$@"
  then
    echo "ERROR: $UVFY_SCRIPT failed" 1>&2
  fi
  UVFY_SCRIPT=
}


uvfy_arg_skip=
for uvfy_arg in "$@"
do
  if test -z "$uvfy_arg_skip"
  then
    case "$uvfy_arg" in
      (-f|--format)         uvfy_arg_skip=1;;
      (-l|--label)          uvfy_arg_skip=1;;
      (-p|--full-paths)     UVFY_FULL_PATHS=1;;
      (--gpg)               uvfy_arg_skip=1;;
      (-x|--hashes)         uvfy_arg_skip=1;;
      (--help)              uvfy_help; exit 0;;
      (-s|--max-size)       uvfy_arg_skip=1;;
      (-xb|--hash-backward) UVFY_HASH_DIRECTION='-1';;
      (-xf|--hash-forward)  UVFY_HASH_DIRECTION='1';;
			(-y|--pretty)         UVFY_OUTPUT_PRETTY=1;;
      (-V|--version)        uvfy_version; exit 0;;
      (--)                  uvfy_output_initialize "$@"; uvfy_runscript;;
      (*)                   uvfy_append_script_argument "$uvfy_arg";;
    esac
  else
    case "$uvfy_last_arg" in
      (-f|--format)         UVFY_OUTPUT_MODE="$uvfy_arg";;
      (-l|--label)          UVFY_BASE_LABEL="$uvfy_arg";;
      (--gpg)               UVFY_GPG="$uvfy_arg";;
      (-x|--hashes)         UVFY_HASHES="${uvfy_arg//,/ /}";;
      (-s|--max-size)       UVFY_OUTPUT_SIZE="$uvfy_arg";;
    esac
    uvfy_arg_skip=
    continue
  fi
  uvfy_last_arg="$uvfy_arg"
done

uvfy_output_initialize "$@"
uvfy_runscript

uvfy_output_end

rm -rf "$UVFY_OUTPUT_TMPDIR"

if test -n "$UVFY_ERROR"
then
  echo "!! WARNING !! some subcommands have failed !! WARNING !!" 1>&2
fi
